export const RESUMES_LIST_REQUEST = 'RESUMES_LIST_REQUEST';
export const RESUMES_LIST_REQUEST_SUCCESS = 'RESUMES_LIST_REQUEST_SUCCESS';
export const RESUMES_LIST_REQUEST_FAIL = 'RESUMES_LIST_REQUEST_FAIL';
