export const RESUME_SINGLE_REQUEST = "RESUME_SINGLE_REQUEST";
export const RESUME_SINGLE_REQUEST_SUCCESS = "RESUME_SINGLE_REQUEST_SUCCESS";
export const RESUME_SINGLE_REQUEST_FAIL = "RESUME_SINGLE_REQUEST_FAIL";

export const RESUME_UPDATE_REQUEST = "RESUME_UPDATE_REQUEST";
export const RESUME_UPDATE_REQUEST_SUCCESS = "RESUME_UPDATE_REQUEST_SUCCESS";
export const RESUME_UPDATE_REQUEST_FAIL = "RESUME_UPDATE_REQUEST_FAIL";

export const RESUME_CREATE_REQUEST = "RESUME_CREATE_REQUEST";
export const RESUME_CREATE_REQUEST_SUCCESS = "RESUME_CREATE_REQUEST_SUCCESS";
export const RESUME_CREATE_REQUEST_FAIL = "RESUME_CREATE_REQUEST_FAIL";
