export const USER_LOG_OUT_REQUEST = "USER_LOG_OUT_REQUEST";
export const USER_LOG_OUT_REQUEST_SUCCESS = "USER_LOG_OUT_REQUEST_SUCCESS";
export const USER_LOG_OUT_REQUEST_FAIL = "USER_LOG_OUT_REQUEST_FAIL";
