export const RESUMES_LOG_OUT_REQUEST = "RESUMES_LOG_OUT_REQUEST";
export const RESUMES_LOG_OUT_REQUEST_SUCCESS =
    "RESUMES_LOG_OUT_REQUEST_SUCCESS";
export const RESUMES_LOG_OUT_REQUEST_FAIL = "RESUMES_LOG_OUT_REQUEST_FAIL";
