export const RESUMES_PROFILE_REQUEST = "RESUMES_PROFILE_REQUEST";
export const RESUMES_PROFILE_REQUEST_SUCCESS =
    "RESUMES_PROFILE_REQUEST_SUCCESS";
export const RESUMES_PROFILE_REQUEST_FAIL = "RESUMES_PROFILE_REQUEST_FAIL";

export const RESUMES_UPDATE_PROFILE_REQUEST = "RESUMES_UPDATE_PROFILE_REQUEST";
export const RESUMES_UPDATE_PROFILE_REQUEST_SUCCESS =
    "RESUMES_UPDATE_PROFILE_REQUEST_SUCCESS";
export const RESUMES_UPDATE_PROFILE_REQUEST_FAIL =
    "RESUMES_UPDATE_PROFILE_REQUEST_FAIL";
