export const RESUMES_SIGN_IN_REQUEST = "RESUMES_SIGN_IN_REQUEST";
export const RESUMES_SIGN_IN_REQUEST_SUCCESS =
    "RESUMES_SIGN_IN_REQUEST_SUCCESS";
export const RESUMES_SIGN_IN_REQUEST_FAIL = "RESUMES_SIGN_IN_REQUEST_FAIL";
