export const USER_SIGN_IN_REQUEST = "USER_SIGN_IN_REQUEST";
export const USER_SIGN_IN_REQUEST_SUCCESS = "USER_SIGN_IN_REQUEST_SUCCESS";
export const USER_SIGN_IN_REQUEST_FAIL = "USER_SIGN_IN_REQUEST_FAIL";
