export const RESUMES_SIGN_UP_REQUEST = "RESUMES_SIGN_UP_REQUEST";
export const RESUMES_SIGN_UP_REQUEST_SUCCESS =
    "RESUMES_SIGN_UP_REQUEST_SUCCESS";
export const RESUMES_SIGN_UP_REQUEST_FAIL = "RESUMES_SIGN_UP_REQUEST_FAIL";
