export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const USER_SIGN_UP_REQUEST_SUCCESS = "USER_SIGN_UP_REQUEST_SUCCESS";
export const USER_SIGN_UP_REQUEST_FAIL = "USER_SIGN_UP_REQUEST_FAIL";
